# Generated by Django 4.2.23 on 2025-08-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='zona',
            field=models.CharField(choices=[('Norte', 'Zona Norte'), ('Centro', 'Zona Centro'), ('Sur', 'Zona Sur')], max_length=10),
        ),
    ]
