# Generated by Django 4.2.24 on 2025-09-04 22:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_region_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='arrendado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InmuebleImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='inmuebles/fotos/')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_inmueble', to='portal.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='inmuebles/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), portal.validators.FileSizeValidator(max_mb=10)])),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_inmueble', to='portal.inmueble')),
            ],
        ),
    ]
