# Generated by Django 4.2.24 on 2025-09-07 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_inmueble_arrendado_inmuebleimagen_inmuebledocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='precio_mensual',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0, message='El precio mensual no puede ser negativo.'), django.core.validators.MaxValueValidator(999999999.9, message='El precio mensual no puede superar 999,999,999.9.')]),
        ),
    ]
