# Generated by Django 4.2.24 on 2025-09-08 18:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import portal.validators


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_inmueble_precio_mensual'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='solicitudes/documentos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), portal.validators.FileSizeValidator(max_mb=10)])),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_solicitud', to='portal.solicitudarriendo')),
            ],
        ),
    ]
