# --- Base image ---
FROM python:3.9-slim

# --- Variables de entorno para Python ---
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# --- Crear un usuario sin privilegios root ---
ARG USER_ID=1000
ARG GROUP_ID=1000
RUN groupadd -g $GROUP_ID appuser && \
    useradd -u $USER_ID -g appuser -s /bin/sh -m appuser

USER appuser

# --- Directorio de trabajo ---
WORKDIR /usr/src/app

# --- Copiar requirements y instalar dependencias ---
COPY --chown=appuser:appuser backend/requirements.txt .
RUN python -m pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# --- Copiar todo el código del backend ---
COPY --chown=appuser:appuser backend/ .

# --- Crear script de arranque ---
RUN echo '#!/bin/bash' > start.sh && \
    echo 'python manage.py migrate --noinput' >> start.sh && \
    echo 'python manage.py collectstatic --noinput' >> start.sh && \
    echo 'python manage.py loaddata portal/fixtures/respaldo_portal_users.json' >> start.sh && \
    echo 'python manage.py runserver 0.0.0.0:8000' >> start.sh && \
    chmod +x start.sh

# --- Comando por defecto ---
CMD ["./start.sh"]
