# Generated by Django 4.2.24 on 2025-09-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfiluser',
            name='tipo_usuario',
        ),
    ]
