# Generated by Django 4.2.24 on 2025-09-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_perfiluser_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
