# Generated by Django 4.2.24 on 2025-09-06 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_inmueble_arrendado_inmuebleimagen_inmuebledocumento'),
        ('users', '0003_perfiluser_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='comuna',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.comuna'),
        ),
    ]
