# Generated by Django 4.2.24 on 2025-09-08 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_perfiluser_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
