# Generated by Django 4.2.24 on 2025-09-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_perfiluser_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfiluser',
            name='tipo_usuario',
            field=models.CharField(choices=[('ARRENDADOR', 'Arrendador'), ('ARRENDATARIO', 'Arrendatario')], default='ARRENDATARIO', max_length=20),
        ),
    ]
