# Generated by Django 4.2.24 on 2025-09-29 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_perfiluser_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfiluser',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotos_perfil/default.jpg', null=True, upload_to='fotos_perfil/'),
        ),
    ]
